# Generated by Django 5.2.9 on 2025-12-31 01:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteChromeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_label', models.CharField(blank=True, default='Support 24/7', max_length=30)),
                ('support_phone', models.CharField(blank=True, default='+34 600 000 000', max_length=40)),
                ('show_mobile_header', models.BooleanField(default=True)),
                ('show_mobile_support', models.BooleanField(default=True)),
                ('navigation', wagtail.fields.StreamField([('item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 24}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use #anchor, /path/ or full URL', 'max_length': 200}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('href', 1)]], {})})),
                ('logo_desktop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo_mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
