# Generated by Django 5.2.9 on 2026-01-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitechromesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navitem'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='href',
            field=models.CharField(max_length=200),
        ),
    ]
