# Generated by Django 5.2.9 on 2025-12-30 00:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('feature_band', 11), ('pricing', 22), ('testimonials', 29), ('faq', 34), ('values', 39), ('stats', 42)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('url', 3)]], {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('primary_button', 4), ('image_1', 5), ('image_2', 5), ('image_3', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 400, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'default': '13k', 'max_length': 10, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Happy customers', 'max_length': 40, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('eyebrow', 7), ('title', 0), ('text', 8), ('button', 4), ('image', 5), ('badge_value', 9), ('badge_label', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'max_length': 50, 'required': False}), 13: ('wagtail.blocks.TextBlock', (), {'max_length': 250, 'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 30, 'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 20, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'monthly', 'max_length': 20, 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 19: ('wagtail.blocks.ListBlock', (18,), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('is_recommended', 14), ('name', 15), ('price', 16), ('period', 17), ('features', 19), ('button', 4)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'max_num': 3, 'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 8), ('helper_title', 12), ('helper_text', 13), ('helper_phone', 7), ('plans', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 24: ('wagtail.blocks.TextBlock', (), {'max_length': 400, 'required': True}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 26: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('quote', 24), ('author_name', 25), ('author_role', 26), ('avatar', 5)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {'max_num': 8, 'min_num': 1}), 29: ('wagtail.blocks.StructBlock', [[('title', 23), ('items', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 31: ('wagtail.blocks.TextBlock', (), {'max_length': 600, 'required': True}), 32: ('wagtail.blocks.StructBlock', [[('question', 30), ('answer', 31)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {'max_num': 10, 'min_num': 1}), 34: ('wagtail.blocks.StructBlock', [[('title', 23), ('items', 33), ('image', 5)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Our values', 'max_length': 80, 'required': False}), 36: ('wagtail.blocks.TextBlock', (), {'max_length': 300, 'required': False}), 37: ('wagtail.blocks.StructBlock', [[('title', 25), ('text', 36), ('image', 5)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {'max_num': 6, 'min_num': 1}), 39: ('wagtail.blocks.StructBlock', [[('title', 35), ('cards', 38)]], {}), 40: ('wagtail.blocks.StructBlock', [[('value', 16), ('label', 2)]], {}), 41: ('wagtail.blocks.ListBlock', (40,), {'max_num': 6, 'min_num': 2}), 42: ('wagtail.blocks.StructBlock', [[('items', 41)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_cta_text',
            field=models.CharField(blank=True, default='Discover', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
